// Copyright 2026 The avif_image_provider authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: type=lint, unused_field, unused_element
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<AvifipDecoder> Function()>()
external ffi.Pointer<AvifipDecoder> avifip_decoder_create();

@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AvifipDecoder>, ffi.Pointer<AvifipFrame>)
>()
external int avifip_decoder_decode_frame(
  ffi.Pointer<AvifipDecoder> decoder,
  ffi.Pointer<AvifipFrame> out_frame,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<AvifipDecoder>)>()
external void avifip_decoder_destroy(ffi.Pointer<AvifipDecoder> decoder);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<AvifipDecoder>, ffi.Int32)
>()
external ffi.Pointer<ffi.Char> avifip_decoder_error_message(
  ffi.Pointer<AvifipDecoder> decoder,
  int result,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AvifipDecoder>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Int32,
    ffi.Pointer<AvifipImageInfo>,
  )
>()
external int avifip_decoder_parse(
  ffi.Pointer<AvifipDecoder> decoder,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  int max_threads,
  ffi.Pointer<AvifipImageInfo> out_info,
);

@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AvifipDecoder>, ffi.Uint32, ffi.Uint32)
>()
external int avifip_decoder_set_target_size(
  ffi.Pointer<AvifipDecoder> decoder,
  int width,
  int height,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> avifip_version();

const int AVIFIP_RESULT_INVALID_ARGUMENT = -1;

const int AVIFIP_RESULT_INVALID_STATE = -3;

const int AVIFIP_RESULT_OK = 0;

const int AVIFIP_RESULT_OUT_OF_MEMORY = -2;

final class AvifipDecoder extends ffi.Opaque {}

final class AvifipFrame extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> pixels;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int row_bytes;

  @ffi.Uint32()
  external int index;

  @ffi.Int64()
  external int duration_us;

  static ffi.Pointer<AvifipFrame> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> pixels,
    required int width,
    required int height,
    required int row_bytes,
    required int index,
    required int duration_us,
  }) => $allocator<AvifipFrame>()
    ..ref.pixels = pixels
    ..ref.width = width
    ..ref.height = height
    ..ref.row_bytes = row_bytes
    ..ref.index = index
    ..ref.duration_us = duration_us;
}

final class AvifipImageInfo extends ffi.Struct {
  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int frame_count;

  @ffi.Int32()
  external int repetition_count;

  @ffi.Uint32()
  external int bit_depth;

  @ffi.Uint32()
  external int has_alpha;

  static ffi.Pointer<AvifipImageInfo> $allocate(
    ffi.Allocator $allocator, {
    required int width,
    required int height,
    required int frame_count,
    required int repetition_count,
    required int bit_depth,
    required int has_alpha,
  }) => $allocator<AvifipImageInfo>()
    ..ref.width = width
    ..ref.height = height
    ..ref.frame_count = frame_count
    ..ref.repetition_count = repetition_count
    ..ref.bit_depth = bit_depth
    ..ref.has_alpha = has_alpha;
}
