import 'package:code_assets/code_assets.dart';

/// Generates the files that dav1d's Meson build would normally generate.
///
/// The values mirror what `meson setup` detects for each platform with a
/// recent toolchain (Android NDK r27+, Xcode 15+, Clang 16+, MSVC 2022).
class Dav1dConfig({
  required final OS os,
  required final Architecture architecture,

  /// Whether the SIMD assembly is compiled in.
  required final bool asm,

  required final bool msvc,

  required final String version,
}) {
  bool get _isApple => os == OS.macOS || os == OS.iOS;
  bool get _isLinuxLike => os == OS.linux || os == OS.android;
  bool get _isAarch64 => architecture == Architecture.arm64;
  bool get _isArm => architecture == Architecture.arm;
  bool get _isX86 =>
      architecture == Architecture.x64 || architecture == Architecture.ia32;
  bool get _isRiscv =>
      architecture == Architecture.riscv32 ||
      architecture == Architecture.riscv64;

  /// Symbols get a leading underscore on these platforms.
  bool get _prefix =>
      _isApple || (os == OS.windows && architecture == Architecture.ia32);

  String get configH {
    final defines = <String, Object>{
      'ARCH_AARCH64': _isAarch64,
      'ARCH_ARM': _isArm,
      'ARCH_LOONGARCH': false,
      'ARCH_LOONGARCH32': false,
      'ARCH_LOONGARCH64': false,
      'ARCH_PPC64LE': false,
      'ARCH_RISCV': _isRiscv,
      'ARCH_RV32': architecture == Architecture.riscv32,
      'ARCH_RV64': architecture == Architecture.riscv64,
      'ARCH_X86': _isX86,
      'ARCH_X86_32': architecture == Architecture.ia32,
      'ARCH_X86_64': architecture == Architecture.x64,
      'CONFIG_8BPC': true,
      'CONFIG_16BPC': true,
      'CONFIG_LOG': true,
      'ENDIANNESS_BIG': false,
      'HAVE_ASM': asm,
      'HAVE_AS_FUNC': false,
      'HAVE_C11_GENERIC': !msvc,
      'HAVE_CLOCK_GETTIME': os != OS.windows,
      'HAVE_DLSYM': os == OS.linux,
      'HAVE_ELF_AUX_INFO': false,
      'HAVE_GETAUXVAL': _isLinuxLike && (_isAarch64 || _isArm || _isRiscv),
      'HAVE_IO_H': os == OS.windows,
      'HAVE_MEMALIGN': _isLinuxLike,
      'HAVE_POSIX_MEMALIGN': os != OS.windows,
      'HAVE_ALIGNED_ALLOC': false,
      'HAVE_PTHREAD_GETAFFINITY_NP': os == OS.linux,
      'HAVE_PTHREAD_SETAFFINITY_NP': os == OS.linux,
      'HAVE_PTHREAD_NP_H': false,
      'HAVE_PTHREAD_SETNAME_NP': _isLinuxLike || _isApple,
      'HAVE_PTHREAD_SET_NAME_NP': false,
      'HAVE_SIGACTION': os != OS.windows,
      'HAVE_SYS_TYPES_H': true,
      'HAVE_UNISTD_H': os != OS.windows,
      'TRIM_DSP_FUNCTIONS': true,
      if (_prefix) 'PREFIX': true,
    };

    final gasAarch64 = asm && _isAarch64;
    defines.addAll({
      'HAVE_AS_ARCH_DIRECTIVE': gasAarch64,
      for (final extension in ['DOTPROD', 'I8MM', 'SVE', 'SVE2']) ...{
        'HAVE_AS_ARCHEXT_${extension}_DIRECTIVE': gasAarch64,
        'HAVE_$extension': gasAarch64,
      },
    });

    final buffer = StringBuffer()
      ..writeln('// Generated by avif_image_provider/hook/build.dart.')
      ..writeln('#ifndef DAV1D_CONFIG_H_GENERATED')
      ..writeln('#define DAV1D_CONFIG_H_GENERATED');
    for (final MapEntry(:key, :value) in defines.entries) {
      buffer.writeln('#define $key ${value == true ? 1 : 0}');
    }
    if (gasAarch64) {
      buffer.writeln('#define AS_ARCH_LEVEL armv8.6-a+crc');
    }
    if (asm && (_isAarch64 || _isArm)) {
      // The objects are always position independent.
      buffer.writeln('#define PIC 3');
    }
    if (os == OS.windows) {
      buffer
        ..writeln('#define _WIN32_WINNT 0x0601')
        ..writeln('#ifndef UNICODE')
        ..writeln('#define UNICODE 1')
        ..writeln('#endif')
        ..writeln('#ifndef _UNICODE')
        ..writeln('#define _UNICODE 1')
        ..writeln('#endif')
        ..writeln('#define _CRT_DECLARE_NONSTDC_NAMES 1');
    }
    buffer.writeln('#endif');
    return buffer.toString();
  }

  String get configAsm {
    final x64 = architecture == Architecture.x64;
    final stackAlignment = x64 || os == OS.linux || _isApple ? 16 : 4;
    final buffer = StringBuffer()
      ..writeln('; Generated by avif_image_provider/hook/build.dart.')
      ..writeln('%define ARCH_X86_32 ${x64 ? 0 : 1}')
      ..writeln('%define ARCH_X86_64 ${x64 ? 1 : 0}')
      ..writeln('%define FORCE_VEX_ENCODING 0')
      ..writeln('%define PIC 1')
      ..writeln('%define STACK_ALIGNMENT $stackAlignment')
      ..writeln('%define private_prefix dav1d');
    if (_prefix) {
      buffer.writeln('%define PREFIX 1');
    }
    return buffer.toString();
  }

  String get nasmFormat {
    final bits = architecture == Architecture.x64 ? '64' : '32';
    return switch (os) {
      OS.windows => 'win$bits',
      OS.macOS || OS.iOS => 'macho$bits',
      _ => 'elf$bits',
    };
  }

  String get vcsVersionH =>
      '// Generated by avif_image_provider/hook/build.dart.\n'
      '#define DAV1D_VERSION "$version"\n';
}
